### ISSUE TITLE
MATLAB script throwing error on TrainFiles line 36 of CreateDatabase.m

### ISSUE THREAD

**Issue by ctargon** [CUFCTFACE/face-recognition#15]
not sure when someone last modified this file, but its throwing an error of the following:

>> run_ica(false)
Error using vertcat
Number of fields in structure arrays being concatenated do not match. Concatenation of structure arrays requires that
these arrays have the same set of fields.

Error in CreateDatabase (line 36)
    TrainFiles = [TrainFiles; entries];

Anyone recently change this file?

**Comment by arlindohall** [comment]
Do you have the wrong folder name for where the images are? Did you run it
with the script?


======================

Miller Hall
Computer Engineering
Clemson University 2016

**Comment by ctargon** [comment]
yep me and Will both ran it with the scripts and without the scripts. still same errors

**Comment by arlindohall** [comment]
Did we ever resolve this?

**Comment by ctargon** [comment]
So the issue is primarily a MacOS issue.  MacOS doesn't have the "shuf" command that is standard in linux. You can download a package that installs it as "gshuf" for MacOS so we could change a script to use that command when running on MacOS possibly. Additionally, Matlab is reading the orl_faces directory and including .DS_Store (a MacOS hidden file) and "." and "..", which was crashing the code.  I think this is primarily a MacOS issue that we can talk about at the next meeting, but for now we can close this issue.
