### ISSUE TITLE
ica.c line 238

### ISSUE THREAD

**Issue by ctargon** [CUFCTFACE/face-recognition#18]
When debugging ica, i noticed an error is occurring at line 238 in ica.c.  The product between x_tran and w is returning NaNs from the m_product function.... Anyone ever have issues with m_product? It uses a BLAS function so I would assume it is correct. I do not believe this error should be occurring based on analysis of X_tran and w.

**Comment by bentsherman** [comment]
This issue has been resolved by my most recent commit, discussion continued in the main ICA issue.
